### ISSUE TITLE
support WebAssembly

### ISSUE THREAD

**Issue by oligamiq** [fitzgen/is_executable#16]
Do you have plans to support WebAssembly (Wasm)?

**Comment by fitzgen** [comment]
I have no plans on implementing it myself, but I am open to PRs.

**Comment by oligamiq** [comment]
Is it acceptable to implement something that always returns false?

**Comment by fitzgen** [comment]
Yeah that should be fine

**Comment by oligamiq** [comment]
https://github.com/fitzgen/is_executable/pull/17
