### ISSUE TITLE
Check for extensions defined in PATHEXT on Windows

### ISSUE THREAD

**Issue by martonlanga** [fitzgen/is_executable#5]
[Currently on Windows executables with extensions defined in `PATHEXT` are ignored](https://stackoverflow.com/a/7839178).

Is this something you would support in your library?

#### Existing implementation examples

- https://github.com/nushell/nushell/blob/93e8f6c05e1e1187d5b674d6b633deb839c84899/crates/nu-cli/src/completion/command.rs#L87
- https://github.com/wez/wezterm/blob/a034730373c341aa078765c081fcb32168b1974f/pty/src/cmdbuilder.rs#L215

**Comment by alpha-tango-kilo** [comment]
I could probably write a PR for this, given the example code seems pretty clear.

@martonlanga what's the use case for this though over what the library already provides? Are there some cases where PATHEXT will determine a file executable where this crate wouldn't, or is this just an alternative implementation?

**Comment by martonlanga** [comment]
@alpha-tango-kilo I've replaced `is_executable` in my project with nushell's sample because the current version of this crate doesn't recognize certain executables as such.

Usually it's an external command that gets ignored (eg.: `yarn.cmd`).

**Comment by alpha-tango-kilo** [comment]
Okay, so does that make it a complete replacement for the current implementation or should it complement it?

I would imagine a file with its extension removed would be classified as runnable by this crate but not when tested using `PATHEXT`, are you able to confirm this?

**Comment by martonlanga** [comment]
I'm fine with a complete replacement, but you should ask @fitzgen about this.

Not entirely sure what you mean by this. Currently this crate only checks whether the provided path is executable or not. On Windows, I would expect this library to also check against the path joined with all the extensions defined in `PATHEXT`.

So if `PATH_TO_YARN\yarn` is not a valid path, it should check whether `PATH_TO_YARN\yarn.exe`,  `PATH_TO_YARN\yarn.cmd`, ... is a valid path.
